# SPDX-FileCopyrightText: 2022 Rick de Jager <rickdejager99@gmail.com>
# SPDX-FileCopyrightText: 2025 VaiTon <eyadlorenzo@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-only

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "frontend"
    schedule:
      interval: "weekly"

  - package-ecosystem: gomod
    directory: services/
    schedule:
      interval: "weekly"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: /
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker-compose"
    directory: /
    schedule:
      interval: "weekly"
