version: 2
updates:
  - package-ecosystem: "npm"
    directory: "frontend"
    schedule:
      interval: "weekly"

  - package-ecosystem: gomod
    directory: services/go-importer
    schedule:
      interval: "weekly"

  - package-ecosystem: pip
    directory: services/api
    schedule:
      interval: "weekly"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: /
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker-compose"
    directory: /
    schedule:
      interval: "weekly"
