services:
  frontend:
    build: frontend
    image: tulip-frontend:latest
    restart: unless-stopped
    ports:
      - "3000:3000"

    depends_on:
      - mongo
      - api

    environment:
      API_SERVER_ENDPOINT: http://api:5000/

  api:
    build:
      context: services/
      target: api
    restart: unless-stopped

    depends_on:
      - mongo

    volumes:
      - ${TRAFFIC_DIR}:/traffic:ro

    environment:
      TULIP_MONGO: mongo:27017
      TULIP_TRAFFIC_DIR: /traffic
      FLAG_REGEX: ${FLAG_REGEX}
      TICK_START: ${TICK_START}
      TICK_LENGTH: ${TICK_LENGTH}
      VM_IP: ${VM_IP}
      GAME_SERVICES: ${GAME_SERVICES}

  assembler:
    build:
      context: services/
      target: assembler

    volumes:
      - ${TRAFFIC_DIR}:/traffic:ro

    restart: unless-stopped
    depends_on:
      - mongo

    environment:
      TULIP_WATCH_DIR: /traffic
      TULIP_FLUSH_INTERVAL: "30s"
      TULIP_CONNECTION_TIMEOUT: "1m"

      TULIP_TCP_LAZY: "true"
      TULIP_EXPERIMENTAL: "true"
      TULIP_NONSTRICT: "true"

      TULIP_MONGO: mongo:27017
      TULIP_FLAG: ${FLAG_REGEX}

  ingestor:
    build:
      context: services/
      target: ingestor
    restart: unless-stopped

    ports:
      - "${INGESTOR_ADDR}:9999"
    volumes:
      - ${TRAFFIC_DIR}:/traffic

    environment:
      TULIP_DEST_DIR: /traffic

      TULIP_ROTATE_INTERVAL: "${INGESTOR_ROTATE}"

  enricher:
    build:
      context: services/
      target: enricher
    restart: unless-stopped
    depends_on:
      - mongo
      - redis
    environment:
      TULIP_MONGO: mongo:27017
      REDIS_URL: redis://redis:6379

  mcp:
    build:
      context: services/
      target: mcp
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      MONGO_HOST: mongo:27017

  suricata:
    build: services/suricata
    depends_on:
      - redis
    restart: unless-stopped
    volumes:
      - ./suricata.rules:/var/lib/suricata/rules/suricata.rules:ro
      - ${TRAFFIC_DIR}:/traffic:ro
    environment:
      WATCH_DIR: /traffic
      REDIS_HOST: redis
      REDIS_PORT: 6379

    tty: true

  redis:
    hostname: redis
    image: redis:8
    restart: unless-stopped

  mongo:
    image: mongo:8
    restart: unless-stopped
    ports:
      - "127.0.0.1:27017:27017" # Only expose to localhost
