services:
  frontend:
    build: frontend
    image: tulip-frontend:latest
    restart: unless-stopped
    ports:
      - "3000:3000"

    depends_on:
      - mongo
      - api

    environment:
      API_SERVER_ENDPOINT: http://api:5000/

  api:
    build:
      context: services/
      target: api
    restart: unless-stopped

    depends_on:
      - mongo

    volumes:
      - ${TRAFFIC_DIR_HOST}:${TRAFFIC_DIR_DOCKER}:ro

    environment:
      TULIP_MONGO: ${TULIP_MONGO}
      TULIP_TRAFFIC_DIR: ${TRAFFIC_DIR_DOCKER}
      FLAG_REGEX: ${FLAG_REGEX}
      TICK_START: ${TICK_START}
      TICK_LENGTH: ${TICK_LENGTH}
      VM_IP: ${VM_IP}
      GAME_SERVICES: ${GAME_SERVICES}

  assembler:
    build:
      context: services/
      target: assembler

    ports:
      - "9999:9999"

    restart: unless-stopped

    depends_on:
      - mongo

    environment:
      TULIP_LISTEN: ":9999"
      TULIP_MONGO: ${TULIP_MONGO}
      TULIP_FLAG: ${FLAG_REGEX}

      TULIP_FLUSH_INTERVAL: "30s"
      TULIP_CONNECTION_TIMEOUT: "1m"

      TULIP_TCP_LAZY: "true"
      TULIP_EXPERIMENTAL: "true"
      TULIP_NONSTRICT: "true"

    extra_hosts:
      - "host.docker.internal:host-gateway"

  enricher:
    build:
      context: services/
      target: enricher
    restart: unless-stopped
    depends_on:
      - mongo
      - redis
    environment:
      TULIP_MONGO: ${TULIP_MONGO}
      REDIS_URL: redis://redis:6379

  mcp:
    build:
      context: services/
      target: mcp
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      MONGO_HOST: ${TULIP_MONGO}

  suricata:
    build: services/suricata
    depends_on:
      - redis
    restart: unless-stopped
    volumes:
      - ./suricata.rules:/var/lib/suricata/rules/suricata.rules:ro
    environment:
      PCAP_OVER_IP: ${PCAP_OVER_IP}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    extra_hosts:
      - "host.docker.internal:host-gateway" # for PCAP-over-ip
    tty: true

  redis:
    hostname: redis
    image: redis:8
    restart: unless-stopped

  mongo:
    image: mongo:8
    restart: unless-stopped
    ports:
      - "127.0.0.1:27017:27017" # Only expose to localhost
