on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  go-importer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.24"

      - run: cd services/go-importer

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build ./...

      - name: Run tests
        run: go test ./...
